### ISSUE TITLE
Something went wrong with my setup

### ISSUE THREAD

**Issue by linuxenko** [hyperdivision/hid#1]
Hi :)

I've successfully installed the module into a fresh(test) project, but there is some problem with a very first run. Lets say, it is just a single line program that looks like this:

```js
var hid = require('hid');
```

When I try to run the app, I got the following thing:

```
node: symbol lookup error: node_modules/hid/build/Release/hidapi.node: undefined symbol: napi_add_env_cleanup_hook
```

Node's version is `v8.10.0`, maybe it is a problem ? Which version of node you'd recommend to try ?

**Comment by emilbayes** [comment]
I think you need to be on 8.11 for this to work: https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_n_api_version_matrix

**Comment by linuxenko** [comment]
The same with `v8.11.4` , I'm going to try it with latest LTS version.

**Comment by linuxenko** [comment]
Oh, finally, `v10.16.3` runs without the error. Thank you )

**Comment by emilbayes** [comment]
@linuxenko Did it rebuild on 8.11.2 for you? Or on LTS? It's set up with prebuilds so it shouldn't but just checked `8.11.2` on my macOS and it rebuilt for some reason ...

**Comment by linuxenko** [comment]
I've reinstalled it (made a fresh, test project) on `v8.11.4` and got the same error message. With LTS the message simple dissapears, I've reinstalled it, (this time it wasn't compiling from source codes) and it runs without the message.

**Comment by emilbayes** [comment]
Yeah 8.11.x didn't work for me, but 8.12.x did

**Comment by emilbayes** [comment]
Unless I'm reading the compat matrix wrong, it seems that the docs are wrong. At least this is one case where 8.11.x didn't support N-API version 3, but 8.12.x did

**Comment by linuxenko** [comment]
At least it was a good reason to upgrade my node , lol ))

**Comment by emilbayes** [comment]
😄
