### ISSUE TITLE
hid.enumerate(0, 0) error

### ISSUE THREAD

**Issue by GanZhiXiong** [hyperdivision/hid#2]
![image](https://user-images.githubusercontent.com/27394631/65566180-a9441800-df84-11e9-88c8-bb38ada6afab.png)

**Comment by emilbayes** [comment]
Hi, looks like something has gone wrong with the electron loading. Which version are you using?

It works fine here with this version:

![image](https://user-images.githubusercontent.com/416524/65597318-1f527a00-df99-11e9-9a2c-5157214dd07d.png)

**Comment by emilbayes** [comment]
Also tried it on latest electron:

![image](https://user-images.githubusercontent.com/416524/65598144-0d71d680-df9b-11e9-850a-0ac222bf6d0e.png)
